service: serverless-simple-http-endpoint

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  region: us-east-1

functions:
  hello:
    handler: index.handler
    events:
      - http:
          path: /
          method: get
